version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/log/nginx
    restart: unless-stopped
    container_name: language-learning-frontend